### ISSUE TITLE
error when python can't decode UTF8 file

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#283]
Python can throw errors like 

```
Traceback (most recent call last):
  File "Resources/Scripts/mergeAnnex60Script.py", line 23, in <module>
    mer.merge(overwrite_reference_results=True)
  File "/Library/Python/2.7/site-packages/buildingspy/development/merger.py", line 378, in merge
    self._copy_rename(srcFil, new_file, rep)
  File "/Library/Python/2.7/site-packages/buildingspy/development/merger.py", line 136, in _copy_rename
    for _, lin in enumerate(f_sou):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 302, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8_sig.py", line 66, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 11: invalid start byte
```

when merging a file that is in an incorrect format. The offending file name should be returned with instructions to fix the problem.

**Comment by Mathadon** [comment]
this was already fixed when pulling the latest version of the master..

**Comment by thorade** [comment]
I think it is related to #223
