### ISSUE TITLE
move_class fails to move files on Windows

### ISSUE THREAD

**Issue by FWuellhorst** [lbl-srg/BuildingsPy#514]
When using `move_class` on windows, the move mos part fails:
```
>>> r.move_class("IBPSA.Fluid.HeatPumps.Examples.ReversibleCarnotWithLosses_OneRoomRadiator", "IBPSA.Fluid.HeatPumps.ModularReversible.Examples.ReversibleCarnotWithLosses_OneRoomRadiator")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\05_Programme\Anaconda3\envs\pyBESMod\lib\site-packages\buildingspy\development\refactor.py", line 699, in move_class
    _move_mos_file(source, target)
  File "D:\05_Programme\Anaconda3\envs\pyBESMod\lib\site-packages\buildingspy\development\refactor.py", line 346, in _move_mos_file
    targetMosFile = sourceMosFile.replace(os.path.join(*sourceFile.split("/")[1:]),
TypeError: join() missing 1 required positional argument: 'path'
>>>
```
The `sourceFile` and `targetFile` equal:
```
IBPSA\Fluid\HeatPumps\Examples\ReversibleCarnotWithLosses_OneRoomRadiator.mo IBPSA\Fluid\HeatPumps\ModularReversible\Examples\ReversibleCarnotWithLosses_OneRoomRadiator.mo
```
`os.path.join` returns the path with backslash in `get_modelica_file_name`. 
Using `.split(os.path.sep)` in all buildingspy cases should be more robust (at least in refactor.py).

**Comment by mwetter** [comment]
@FWuellhorst : Thanks for reporting. The above PR should correct this.
