### ISSUE TITLE
Bug when using other executable than 'dymola'

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#77]
I have two dymola installations. When trying to use an old version, using: 
```
tester=r.Tester(executable='dymola_old') 
```

I get the following error:

```
Traceback (most recent call last):
  File "RunUnitTests.py", line 40, in <module>
    tester.run()
  File "/usr/local/lib/python2.7/dist-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/development/regressiontest.py", line 2137, in run
    self._write_runscripts()
  File "/usr/local/lib/python2.7/dist-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/development/regressiontest.py", line 1875, in _write_runscripts
    "checkCommand": self._getModelCheckCommand(absMosFilNam).replace("\\","/"),
AttributeError: 'NoneType' object has no attribute 'replace
```
is this a bug?

**Comment by mwetter** [comment]
This is a bug. `r.Tester(...)` should immediately return if executable is not `dymola` or `omc`. The reason is because the scripts for the regression tests are tool specific, and this flag is used to determine what scripts need to be written.

If you want to use your old Dymola, I suggest you make a symbolic link, or set the PATH variable so that it picks up the old installation.
